#  ____     ____   ____       _                                      
# |  _ \   / ___| | __ )     / \     _ __   _ __ ___     ___    _ __ 
# | |_) | | |  _  |  _ \    / _ \   | '__| | '_ ` _ \   / _ \  | '__|
# |  _ <  | |_| | | |_) |  / ___ \  | |    | | | | | | | (_) | | |   
# |_| \_\  \____| |____/  /_/   \_\ |_|    |_| |_| |_|  \___/  |_|   
#         By fernanACM and mohagames  

#Color your armor with RGB codes! 
#A simple RGB menu that will allow you to color your leather armor to your liking.

#Here you can get the rgb codes for the plugin: https://www.rapidtables.com/web/color/RGB_Color.html

#Examples RGB:
#Button SINGLE --X

#Single: "r, g, b" = 233,112,341

#Button MULTIPLE --X
#Multiple: 

#Helmet: "r, g, b" = 217,188,172
#Chestplate: "r, g, b" = 188,372,299
#Pants: "r, g, b" = 352,261,222
#Boots: "r, g, b" = 255,255,255
#------------------------

# Prefix RGBArmor plugin:
Prefix: "§l§7[§5RGB§dArmor§7]§8»§r "
#------------------------------------

# Messages plugin:
RGB-CODE: "§gThis RGB code is invalid!"

Error: "§gPlease fill in all fields"

#------------------------------------

# MENU MESSAGE:

MenuContent: "§l§eSingle:§r Make a whole set with the same color\n\n§l§eMultiple:§r Customise each armor piece\n\n"
# Buttons
ButtonSingle: "§l§9Single\n§r§0Click"
ButtonMultiple: "§l§bMultiple\n§r§0Click"
ButtonExit: "§l§4Exit\n§r§0Menu"